---
- name: Setup macOS environment
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Check if Zsh is installed
      command: zsh --version
      register: zsh_installed
      failed_when: zsh_installed.stderr != ''
      ignore_errors: yes

    - name: Install Zsh
      homebrew:
        name: zsh
        state: present
      when: zsh_installed is failed

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
      become: no

    - name: Check if NVM is installed
      command: nvm --version
      register: nvm_installed
      failed_when: nvm_installed.stderr != ''
      ignore_errors: yes

    - name: Install NVM
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      when: nvm_installed is failed

    - name: Source NVM
      shell: 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
      args:
        executable: /bin/zsh
      when: nvm_installed is failed

    - name: Check if Node.js is installed
      command: node --version
      register: node_installed
      failed_when: node_installed.stderr != ''
      ignore_errors: yes

    - name: Install Node.js with NVM
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install node
      args:
        executable: /bin/zsh
      environment:
        HOME: "{{ ansible_env.HOME }}"
      when: node_installed is failed

    - name: Check if PNPM is installed
      command: pnpm --version
      register: pnpm_installed
      failed_when: pnpm_installed.stderr != ''
      ignore_errors: yes

    - name: Install pnpm
      npm:
        name: pnpm
        global: yes
      when: pnpm_installed is failed
