---
- name: Setup Dotfiles
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check if ~/dotfiles exists
      stat:
        path: ~/dotfiles
      register: dotfiles_dir

    - name: Clone dotfiles repository
      git:
        repo: git@github.com:KrokoYR/dotfiles.git
        dest: ~/dotfiles
        clone: yes
        update: yes
      when: not dotfiles_dir.stat.exists

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: ~/.oh-my-zsh
      become: no

    - name: Install Powerlevel10k theme
      git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
        clone: yes
        update: yes
      environment:
        ZSH_CUSTOM: ~/.oh-my-zsh/custom
      become: no

    - name: Install zsh-autosuggestions plugin
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
        clone: yes
        update: yes
      environment:
        ZSH_CUSTOM: ~/.oh-my-zsh/custom
      become: no

    - name: Replace .zshrc with the custom version
      file:
        src: ~/dotfiles/zshrc
        dest: ~/.zshrc
        state: link
        force: yes
      become: no

    - name: Ensure Neovim config directory exists
      file:
        path: ~/.config/nvim
        state: directory
      when: not dotfiles_dir.stat.exists

    - name: Create symbolic link for Neovim config
      file:
        src: ~/dotfiles/nvim
        dest: ~/.config/nvim
        state: link
        force: yes
      when: not dotfiles_dir.stat.exists
