---
- name: Setup Dotfiles
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone dotfiles repository
    git:
      repo: https://github.com/KrokoYR/dotfiles.git
      dest: ~/dotfiles
      clone: yes
      update: yes

  - name: Ensure Neovim config directory exists
    file:
      path: ~/.config/nvim
      state: directory

  - name: Create symbolic link for .zshrc
    file:
      src: ~/dotfiles/zshrc
      dest: ~/.zshrc
      state: link
      force: yes

  - name: Create symbolic link for Neovim config
    file:
      src: ~/dotfiles/nvim
      dest: ~/.config/nvim
      state: link
      force: yes
