---
- name: Setup Dotfiles
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check if ~/dotfiles exists
      stat:
        path: ~/dotfiles
      register: dotfiles_dir

    - name: Clone dotfiles repository
      git:
        repo: git@github.com:KrokoYR/dotfiles.git
        dest: ~/dotfiles
        clone: yes
        update: yes
      when: not dotfiles_dir.stat.exists

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: ~/.oh-my-zsh
      become: no
      when: not dotfiles_dir.stat.exists

    - name: Install Powerlevel10k theme
      git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
        clone: yes
        update: yes
      environment:
        ZSH_CUSTOM: ~/.oh-my-zsh/custom
      become: no
      when: not dotfiles_dir.stat.exists

    - name: Install zsh-autosuggestions plugin
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
        clone: yes
        update: yes
      environment:
        ZSH_CUSTOM: ~/.oh-my-zsh/custom
      become: no
      when: not dotfiles_dir.stat.exists

    - name: Replace .zshrc with the custom version
      file:
        src: ~/dotfiles/zshrc
        dest: ~/.zshrc
        state: link
        force: yes
      become: no
      when: not dotfiles_dir.stat.exists

    - name: Ensure Neovim config directory exists
      file:
        path: ~/.config/nvim
        state: directory
      when: not dotfiles_dir.stat.exists

    - name: Create symbolic link for Neovim config
      file:
        src: ~/dotfiles/nvim
        dest: ~/.config/nvim
        state: link
        force: yes
      when: not dotfiles_dir.stat.exists

    - name: Find files in the source directory
      find:
        paths: "~/dotfiles/bin/.local/scripts/"
        depth: 1
      register: files_to_link

    - name: Create symbolic links for each found script file
      file:
        src: "{{ item.path }}"
        dest: "/usr/local/bin/{{ item.path | basename }}"
        state: link
        force: yes
      loop: "{{files_to_link.files}}"
      become: true
